### ISSUE TITLE
Make dist fails on Python 3.8

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-microphone-cli-hermes#5]
PyInstaller fails on Python 3.8.

See our [GitHub Action runner](https://github.com/rhasspy/rhasspy-microphone-cli-hermes/runs/377013561) that discovered this.

Relevant traceback:
```
7340 INFO: checking PYZ
7341 INFO: Building PYZ because PYZ-00.toc is non existent
7341 INFO: Building PYZ (ZlibArchive) pyinstaller/build/rhasspymicrophone_cli_hermes/PYZ-00.pyz
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.0/x64/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "rhasspymicrophone_cli_hermes.spec", line 20, in <module>
    pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
Makefile:40: recipe for target 'pyinstaller' failed
```
On my local machine with Python 3.7.5 it doesn't return this error.

It's apparently a [known issue](https://github.com/pyinstaller/pyinstaller/issues/4265). Would it make sense to temporarily install pyinstaller [from Git](https://github.com/pyinstaller/pyinstaller/issues/4265#issuecomment-561828277)? This one should do the trick:

```
pip install git+git://github.com/pyinstaller/pyinstaller.git@9dd34bdfbaeaa4e0459bd3051d1caf0c7d75073f
```

**Comment by koenvervloesem** [comment]
I have fixed this temporarily by installing PyInstaller from Git. I'll keep an eye on the appearance of Python 3.8 support in an official PyInstaller version.
